### ISSUE TITLE
Placement doesn't take into account terrain height

### ISSUE THREAD

**Issue by Janooba** [AndyFenwick/FenceLayout#1]
Looks like the placement doesn't take into account the height of the terrain object itself. I fixed it by changing any instance where the heightmap was sampled to include it.

Example:
```csharp
if (newPos != m_fenceLayout.FencePoints[i])
{
	if (m_mainTerrain)
	{
		newPos.y = m_mainTerrain.SampleHeight(newPos) + m_mainTerrain.GetPosition().y;
	}

	m_fenceLayout.FencePoints[i] = newPos;
}
```

**Comment by AndyFenwick** [comment]
Thanks, should be fixed now. All SampleHeight calls are done through a new SampleTerrainHeight function which includes the terrain position.
